name: x86_64

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for x86_64-unknown-linux-gnu
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          repository: rapiz1/rathole
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        env:
          SOURCE_DATE_EPOCH: 0
          RUSTFLAGS: -C opt-level=3 -C target-cpu=ivybridge
        run: |
          cargo build --release --no-default-features --features server,tls
      - uses: actions/upload-artifact@v3
        with:
          name: rathole-x86_64-unknown-linux-gnu
          path: target/release/rathole
          if-no-files-found: error
